language: php

env:
  - TRAVIS=true

php:
  - 7.1
  - 7.0
  - 5.6

before_script:
  - composer install
  - mysql -e 'create database IF NOT EXISTS test;'

script: vendor/phpunit/phpunit/phpunit --configuration test/phpunit.xml

branches:
  only:
    - master
