language: php

env:
  - TRAVIS=true

php:
  - 7.1
  - 7.0
  - 5.6	
  - 5.5

before_script:
  - composer install
  - mysql -e 'create database IF NOT EXISTS test;'
    
script: phpunit

branches:
  only:
    - master
